name: Publish stories if changed

on:
  push:
    branches:
      - main
    paths:
      - stories/**
      - src/components/**
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v2

      - name: '🔧 setup node'
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: '📦 build Storybook'
        run: pnpx build-storybook

      - name: '🚀 deploy static'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: false
